mysql wikipediaviews -e "select distinct pagename,tag from pagetags where \
  tag = 'Altruism concepts' \
  or tag = 'American Civil War' \
  or tag = 'American female tennis players' \
  or tag = 'American film actresses' \
  or tag = 'American male tennis players' \
  or tag = 'American pornographic film actresses' \
  or tag = 'American soccer players' \
  or tag = 'American television and radio pundits' \
  or tag = 'American television shows and series' \
  or tag = 'Animal welfare' \
  or tag = 'Anti-migration websites' \
  or tag = 'Australian cricketers' \
  or tag = 'Australian female tennis players' \
  or tag = 'Australian male tennis players' \
  or tag = 'Barack Obama' \
  or tag = 'Billionaires' \
  or tag = 'Birds' \
  or tag = 'Bollywood movies' \
  or tag = 'Books' \
  or tag = 'British female tennis players' \
  or tag = 'British male tennis players' \
  or tag = 'Cancer researchers' \
  or tag = 'Cause prioritization' \
  or tag = 'Characters in The Flower in Prison' \
  or tag = 'Charities' \
  or tag = 'Charity review websites' \
  or tag = 'Chess grandmasters' \
  or tag = 'Chinese cities' \
  or tag = 'Chinese Go players' \
  or tag = 'Cities' \
  or tag = 'Cognitive biases' \
  or tag = 'Colors' \
  or tag = 'Community foundations based in the United States' \
  or tag = 'Compiler theory' \
  or tag = 'Conflicts' \
  or tag = 'Conflicts in 2011' \
  or tag = 'Conflicts in 2012' \
  or tag = 'Conflicts in 2013' \
  or tag = 'Conflicts in 2014' \
  or tag = 'Conflicts in 2015' \
  or tag = 'Conflicts in 2016' \
  or tag = 'Contemporary mathematics professors' \
  or tag = 'Continents and subcontinents' \
  or tag = 'Contributions pages of Wikipedia editors who have done paid work for Vipul Naik' \
  or tag = 'Countries' \
  or tag = 'Country healthcare timelines created by Sebastian Sanchez' \
  or tag = 'Cricketers' \
  or tag = 'Deaths by year' \
  or tag = 'Democracy' \
  or tag = 'Development economists' \
  or tag = 'Disease timelines created by Sebastian Sanchez' \
  or tag = 'Division of Korea' \
  or tag = 'Donald Trump' \
  or tag = 'Effective altruism' \
  or tag = 'Eggplant dishes' \
  or tag = 'English cricketers' \
  or tag = 'English-language films' \
  or tag = 'Female poker players' \
  or tag = 'Forecasting' \
  or tag = 'French female tennis players' \
  or tag = 'French male tennis players' \
  or tag = 'Futures studies' \
  or tag = 'Gary Johnson' \
  or tag = 'Go players' \
  or tag = 'Group theory' \
  or tag = 'Health officials' \
  or tag = 'Help pages' \
  or tag = 'Hillary Clinton' \
  or tag = 'Hindu mythology characters' \
  or tag = 'HIV/AIDS researchers' \
  or tag = 'Human cells' \
  or tag = 'Human rights groups' \
  or tag = 'Humanitarian organizations' \
  or tag = 'Indian cities' \
  or tag = 'Indian cricketers' \
  or tag = 'Indian female tennis players' \
  or tag = 'Indian independence movement' \
  or tag = 'Indian journalists' \
  or tag = 'Indian male tennis players' \
  or tag = 'Indian musicians' \
  or tag = 'Indian playback singers' \
  or tag = 'Indian politicians' \
  or tag = 'Indian television shows and series' \
  or tag = 'Insects' \
  or tag = 'Internet protocols' \
  or tag = 'Japanese Go players' \
  or tag = 'Japanese television shows and series' \
  or tag = 'Korean television shows and series' \
  or tag = 'Legal history of Germany' \
  or tag = 'Libertarian intellectuals' \
  or tag = 'Libertarian organizations' \
  or tag = 'Lists by GDP' \
  or tag = 'Machine learning' \
  or tag = 'Malaria' \
  or tag = 'Malaria organizations' \
  or tag = 'Malariologists' \
  or tag = 'Mammals' \
  or tag = 'Mathematicians' \
  or tag = 'Meiji Japan' \
  or tag = 'Migration scholars and activists' \
  or tag = 'Musicians' \
  or tag = 'Neighbourhoods of Delhi' \
  or tag = 'New York City Subway' \
  or tag = 'News and media websites' \
  or tag = 'Online learning' \
  or tag = 'Organizations in philanthropy brand awareness survey' \
  or tag = 'Pages about United States migration laws' \
  or tag = 'Pages created by Adrian Ulloa' \
  or tag = 'Pages created by Adrian Ulloa in 2016' \
  or tag = 'Pages created by Adrian Ulloa in 201608' \
  or tag = 'Pages created by Adrian Ulloa in 201609' \
  or tag = 'Pages created by Alex K. Chen' \
  or tag = 'Pages created by Alex K. Chen before 2015' \
  or tag = 'Pages created by Alex K. Chen in 2015' \
  or tag = 'Pages created by Alex K. Chen in 201504' \
  or tag = 'Pages created by Alex K. Chen in 201505' \
  or tag = 'Pages created by Alex K. Chen in 201506' \
  or tag = 'Pages created by Alex K. Chen in 201507' \
  or tag = 'Pages created by Alex K. Chen in 201508' \
  or tag = 'Pages created by Alex K. Chen in 201509' \
  or tag = 'Pages created by Alex K. Chen in 201510' \
  or tag = 'Pages created by Alex K. Chen in 201511' \
  or tag = 'Pages created by Alex K. Chen in 201512' \
  or tag = 'Pages created by Alex K. Chen in 2016' \
  or tag = 'Pages created by Alex K. Chen in 201601' \
  or tag = 'Pages created by Alex K. Chen in 201602' \
  or tag = 'Pages created by Alex K. Chen in 201603' \
  or tag = 'Pages created by Alex K. Chen in 201604' \
  or tag = 'Pages created by Alex K. Chen in 201605' \
  or tag = 'Pages created by Alex K. Chen in 201606' \
  or tag = 'Pages created by Alex K. Chen in 201607' \
  or tag = 'Pages created by Alex K. Chen in 201608' \
  or tag = 'Pages created by Alex K. Chen in 201609' \
  or tag = 'Pages created by Alex K. Chen in 201610' \
  or tag = 'Pages created by Alex K. Chen in 201612' \
  or tag = 'Pages created by Avi Glozman' \
  or tag = 'Pages created by Avi Glozman in 2016' \
  or tag = 'Pages created by Avi Glozman in 201606' \
  or tag = 'Pages created by Avi Glozman in 201607' \
  or tag = 'Pages created by Avi Glozman in 201608' \
  or tag = 'Pages created by Avi Glozman in 201610' \
  or tag = 'Pages created by Brian Tomasik' \
  or tag = 'Pages created by Charlie Corner' \
  or tag = 'Pages created by Charlie Corner in 2016' \
  or tag = 'Pages created by Charlie Corner in 201607' \
  or tag = 'Pages created by Charlie Corner in 201608' \
  or tag = 'Pages created by Charlie Corner in 201609' \
  or tag = 'Pages created by Charlie Corner in 2017' \
  or tag = 'Pages created by Charlie Corner in 201701' \
  or tag = 'Pages created by Chris Kunin' \
  or tag = 'Pages created by Chris Kunin in 2016' \
  or tag = 'Pages created by Chris Kunin in 201606' \
  or tag = 'Pages created by Chris Kunin in 201607' \
  or tag = 'Pages created by Chris Kunin in 201608' \
  or tag = 'Pages created by Chris Kunin in 201609' \
  or tag = 'Pages created by Chris Kunin in 201610' \
  or tag = 'Pages created by Devansh Dwivedy' \
  or tag = 'Pages created by Devansh Dwivedy in 2016' \
  or tag = 'Pages created by Devansh Dwivedy in 201606' \
  or tag = 'Pages created by Devansh Dwivedy in 201607' \
  or tag = 'Pages created by Devansh Dwivedy in 201611' \
  or tag = 'Pages created by Devansh Dwivedy in 2017' \
  or tag = 'Pages created by Devansh Dwivedy in 201701' \
  or tag = 'Pages created by Eddy Su' \
  or tag = 'Pages created by Eddy Su in 2016' \
  or tag = 'Pages created by Eddy Su in 201606' \
  or tag = 'Pages created by Ethan Bashkansky' \
  or tag = 'Pages created by Ethan Bashkansky about United States tax forms' \
  or tag = 'Pages created by Ethan Bashkansky in 2016' \
  or tag = 'Pages created by Ethan Bashkansky in 201602' \
  or tag = 'Pages created by Ethan Bashkansky in 201604' \
  or tag = 'Pages created by Ethan Bashkansky in 201608' \
  or tag = 'Pages created by Ethan Bashkansky in 201609' \
  or tag = 'Pages created by Ethan Bashkansky in 201610' \
  or tag = 'Pages created by Ethan Bashkansky in 201611' \
  or tag = 'Pages created by Ethan Bashkansky in 2017' \
  or tag = 'Pages created by Ethan Bashkansky in 201701' \
  or tag = 'Pages created by Ethan Bashkansky in 201702' \
  or tag = 'Pages created by Gwern' \
  or tag = 'Pages created by Issa Rice' \
  or tag = 'Pages created by Issa Rice about United States migration forms' \
  or tag = 'Pages created by Issa Rice about United States tax forms' \
  or tag = 'Pages created by Issa Rice in 2016' \
  or tag = 'Pages created by Issa Rice in 201601' \
  or tag = 'Pages created by Issa Rice in 201602' \
  or tag = 'Pages created by Issa Rice in 201603' \
  or tag = 'Pages created by Issa Rice in 201604' \
  or tag = 'Pages created by Issa Rice in 201605' \
  or tag = 'Pages created by Issa Rice in 201606' \
  or tag = 'Pages created by Issa Rice in 201607' \
  or tag = 'Pages created by Issa Rice in 201610' \
  or tag = 'Pages created by Issa Rice in 2017' \
  or tag = 'Pages created by Issa Rice in 201701' \
  or tag = 'Pages created by Jesse Clifton' \
  or tag = 'Pages created by Jesse Clifton in 2016' \
  or tag = 'Pages created by Jesse Clifton in 201604' \
  or tag = 'Pages created by Jesse Clifton in 201605' \
  or tag = 'Pages created by Jesse Clifton in 201606' \
  or tag = 'Pages created by Jesse Clifton in 201607' \
  or tag = 'Pages created by Jesse Clifton in 201608' \
  or tag = 'Pages created by Jesse Clifton in 201609' \
  or tag = 'Pages created by Jesse Clifton in 201611' \
  or tag = 'Pages created by Jesse Clifton in 2017' \
  or tag = 'Pages created by Jesse Clifton in 201701' \
  or tag = 'Pages created by Joey Malandra' \
  or tag = 'Pages created by Joey Malandra in 2016' \
  or tag = 'Pages created by Joey Malandra in 201612' \
  or tag = 'Pages created by Joey Malandra in 2017' \
  or tag = 'Pages created by Joey Malandra in 201701' \
  or tag = 'Pages created by Michael Royzen' \
  or tag = 'Pages created by Michael Royzen in 2016' \
  or tag = 'Pages created by Michael Royzen in 201606' \
  or tag = 'Pages created by Sean Yu' \
  or tag = 'Pages created by Sean Yu in 2016' \
  or tag = 'Pages created by Sean Yu in 201606' \
  or tag = 'Pages created by Sebastian Sanchez' \
  or tag = 'Pages created by Sebastian Sanchez in 2016' \
  or tag = 'Pages created by Sebastian Sanchez in 201604' \
  or tag = 'Pages created by Sebastian Sanchez in 201605' \
  or tag = 'Pages created by Sebastian Sanchez in 201607' \
  or tag = 'Pages created by Sebastian Sanchez in 201608' \
  or tag = 'Pages created by Sebastian Sanchez in 201609' \
  or tag = 'Pages created by Sebastian Sanchez in 201610' \
  or tag = 'Pages created by Sebastian Sanchez in 201611' \
  or tag = 'Pages created by Sebastian Sanchez in 201612' \
  or tag = 'Pages created by Sebastian Sanchez in 2017' \
  or tag = 'Pages created by Sebastian Sanchez in 201701' \
  or tag = 'Pages created by Sergey Yegorov' \
  or tag = 'Pages created by Sergey Yegorov in 2016' \
  or tag = 'Pages created by Sergey Yegorov in 201609' \
  or tag = 'Pages created by Sergey Yegorov in 201610' \
  or tag = 'Pages created by Thomas Foster' \
  or tag = 'Pages created by Thomas Foster in 2016' \
  or tag = 'Pages created by Thomas Foster in 201606' \
  or tag = 'Pages created by Vipul Naik' \
  or tag = 'Pages created by Vipul Naik about finance companies' \
  or tag = 'Pages created by Vipul Naik about migration' \
  or tag = 'Pages created by Vipul Naik about migration history' \
  or tag = 'Pages created by Vipul Naik about people' \
  or tag = 'Pages created by Vipul Naik about technology companies' \
  or tag = 'Pages created by Vipul Naik about United States migration forms' \
  or tag = 'Pages created by Vipul Naik about United States migration laws' \
  or tag = 'Pages created by Vipul Naik about United States migration procedures' \
  or tag = 'Pages created by Vipul Naik in 2005' \
  or tag = 'Pages created by Vipul Naik in 200509' \
  or tag = 'Pages created by Vipul Naik in 200511' \
  or tag = 'Pages created by Vipul Naik in 2006' \
  or tag = 'Pages created by Vipul Naik in 200601' \
  or tag = 'Pages created by Vipul Naik in 200603' \
  or tag = 'Pages created by Vipul Naik in 200604' \
  or tag = 'Pages created by Vipul Naik in 200605' \
  or tag = 'Pages created by Vipul Naik in 200606' \
  or tag = 'Pages created by Vipul Naik in 200607' \
  or tag = 'Pages created by Vipul Naik in 200609' \
  or tag = 'Pages created by Vipul Naik in 200610' \
  or tag = 'Pages created by Vipul Naik in 200611' \
  or tag = 'Pages created by Vipul Naik in 200612' \
  or tag = 'Pages created by Vipul Naik in 2007' \
  or tag = 'Pages created by Vipul Naik in 200701' \
  or tag = 'Pages created by Vipul Naik in 2010' \
  or tag = 'Pages created by Vipul Naik in 201012' \
  or tag = 'Pages created by Vipul Naik in 2011' \
  or tag = 'Pages created by Vipul Naik in 201111' \
  or tag = 'Pages created by Vipul Naik in 2012' \
  or tag = 'Pages created by Vipul Naik in 201205' \
  or tag = 'Pages created by Vipul Naik in 201206' \
  or tag = 'Pages created by Vipul Naik in 201208' \
  or tag = 'Pages created by Vipul Naik in 201211' \
  or tag = 'Pages created by Vipul Naik in 201212' \
  or tag = 'Pages created by Vipul Naik in 2013' \
  or tag = 'Pages created by Vipul Naik in 201301' \
  or tag = 'Pages created by Vipul Naik in 201302' \
  or tag = 'Pages created by Vipul Naik in 201304' \
  or tag = 'Pages created by Vipul Naik in 201305' \
  or tag = 'Pages created by Vipul Naik in 201307' \
  or tag = 'Pages created by Vipul Naik in 201309' \
  or tag = 'Pages created by Vipul Naik in 201310' \
  or tag = 'Pages created by Vipul Naik in 201311' \
  or tag = 'Pages created by Vipul Naik in 201312' \
  or tag = 'Pages created by Vipul Naik in 2014' \
  or tag = 'Pages created by Vipul Naik in 201401' \
  or tag = 'Pages created by Vipul Naik in 201402' \
  or tag = 'Pages created by Vipul Naik in 201403' \
  or tag = 'Pages created by Vipul Naik in 201404' \
  or tag = 'Pages created by Vipul Naik in 201405' \
  or tag = 'Pages created by Vipul Naik in 201406' \
  or tag = 'Pages created by Vipul Naik in 201407' \
  or tag = 'Pages created by Vipul Naik in 201408' \
  or tag = 'Pages created by Vipul Naik in 201409' \
  or tag = 'Pages created by Vipul Naik in 2015' \
  or tag = 'Pages created by Vipul Naik in 201501' \
  or tag = 'Pages created by Vipul Naik in 201502' \
  or tag = 'Pages created by Vipul Naik in 201503' \
  or tag = 'Pages created by Vipul Naik in 201504' \
  or tag = 'Pages created by Vipul Naik in 201505' \
  or tag = 'Pages created by Vipul Naik in 201506' \
  or tag = 'Pages created by Vipul Naik in 201507' \
  or tag = 'Pages created by Vipul Naik in 201508' \
  or tag = 'Pages created by Vipul Naik in 201509' \
  or tag = 'Pages created by Vipul Naik in 201510' \
  or tag = 'Pages created by Vipul Naik in 201511' \
  or tag = 'Pages created by Vipul Naik in 201512' \
  or tag = 'Pages created by Vipul Naik in 2016' \
  or tag = 'Pages created by Vipul Naik in 201601' \
  or tag = 'Pages created by Vipul Naik in 201602' \
  or tag = 'Pages created by Vipul Naik in 201603' \
  or tag = 'Pages created by Vipul Naik in 201604' \
  or tag = 'Pages created by Vipul Naik in 201605' \
  or tag = 'Pages created by Vipul Naik in 201606' \
  or tag = 'Pages created by Vipul Naik in 201607' \
  or tag = 'Pages created by Vipul Naik in 201610' \
  or tag = 'Pages created by Vipul Naik in 201612' \
  or tag = 'Pages created by Vipul Naik in 2017' \
  or tag = 'Pages created by Vipul Naik in 201701' \
  or tag = 'Pages created or significantly edited by Gwern' \
  or tag = 'Pages edited significantly but not created by Amy Zhang' \
  or tag = 'Pages edited significantly but not created by Chris Kunin' \
  or tag = 'Pages edited significantly but not created by Issa Rice' \
  or tag = 'Pages edited significantly but not created by Jesse Clifton' \
  or tag = 'Pages edited significantly but not created by Sergey Yegorov' \
  or tag = 'Pages edited significantly but not created by Vipul Naik' \
  or tag = 'Pages in SurveyMonkey second survey' \
  or tag = 'Pages that redirect to Black' \
  or tag = 'Pages that redirect to Red' \
  or tag = 'Participation' \
  or tag = 'People involved with effective altruism' \
  or tag = 'Philanthropic foundations' \
  or tag = 'Political forecasting' \
  or tag = 'Population ethics' \
  or tag = 'Potato dishes' \
  or tag = 'Presidency timelines' \
  or tag = 'Programming languages' \
  or tag = 'Reptiles' \
  or tag = 'Sex organs' \
  or tag = 'Shades of colors' \
  or tag = 'Shooting-related pages' \
  or tag = 'Songs by Taylor Swift' \
  or tag = 'South Korean Go players' \
  or tag = 'Special ASCII characters' \
  or tag = 'Special pages' \
  or tag = 'Sports' \
  or tag = 'Survey methodology' \
  or tag = 'Taiwanese Go players' \
  or tag = 'Talk pages of Wikipedia editors who have done paid work for Vipul Naik' \
  or tag = 'Taylor Swift' \
  or tag = 'Technology company timelines' \
  or tag = 'Timelines' \
  or tag = 'Tomato dishes' \
  or tag = 'Transit terminology' \
  or tag = 'Turkish television shows and series' \
  or tag = 'United States elections, 2016' \
  or tag = 'United States politicians' \
  or tag = 'United States presidential election debates' \
  or tag = 'United States presidents' \
  or tag = 'United States states' \
  or tag = 'United States visas' \
  or tag = 'Venture capital firms' \
  or tag = 'Web browsers' \
  or tag = 'Web development' \
  or tag = 'Web service companies' \
  or tag = 'Wikipedia editors who have done paid work for Vipul Naik' \
  or tag = 'Wikipedia policies' \
  or tag = 'Wikipedia project pages' \
  or tag = 'World Health Organization officials' \
  " > wv_tags.tsv
